### ISSUE TITLE
In-Component Guard beforeRouteLeave not working

### ISSUE THREAD

**Issue by Armesh** [vuejs/vue-router#1066]
### Vue.js / vue-router versions
2.1.8 / 2.1.1

Happens in Vue SPA app made with webpack vue cli template. Tested with fresh project.

See the details here: https://forum.vuejs.org/t/in-component-guard-beforerouteleave-not-working/4658/1

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

`beforeRouteLeave` is meant to be used on a view component not on the root component

**Comment by Armesh** [comment]
@posva I also tried using the beforeRouteLeave hook in multiple child view components and it still doesn't do anything. E.g below 

```
<template>
  <canvas v-bind:id="'chart-hardsets-program-' + programId" width="400" height="150"></canvas>
</template>

<script>
import Chart from 'chart.js'

export default {
  props: {
    programId: {
      required: true,
      type: Number
    }
  },
  data: function () {...},

  methods: {...},

  beforeRouteLeave (to, from, next) {
    console.log('left child component')
  },
  mounted: function () {...} // mounted
}
</script>
```

**Comment by Armesh** [comment]
Solved here:  https://forum.vuejs.org/t/in-component-guard-beforerouteleave-not-working/4658

**Comment by smarbos** [comment]
Hello! I'm still having this issue. And I see another people having this same problem.
I'm trying to use beforeRouteLeave in a page component using the Vue router.
The beforeRouteLeave never triggers, but beforeRouteEnter does.
I'm using vuejs 2.3.2, node v8.9.4.
If anybody needs help to reproduce, let me know!
Thanks!

**Comment by hsnotebook** [comment]
@smarbos Maybe you are using `beforeRouteLeave` in a sub component.
Check this [issue](https://github.com/vuejs/vue-router/issues/764)

**Comment by dennis2k** [comment]
I've experienced this issue as well - i was autoregistering my components with require context


```
const componentContext = require.context("@/components", true, /\.vue$/);
const pagesContext = require.context("@/crm", true, /\.vue$/);

```

I was registering hooks after i registered my components

```
Component.registerHooks([
    "beforeRouteEnter",
    "beforeRouteLeave",
    "beforeRouteUpdate" // for vue-router 2.2+
]);

```

When moving the hooks registration above the component registration - it worked perfectly

**Comment by geni94** [comment]
The component using `beforeRouteLeave` or `beforeRouteUpdate` needs to be declared as a path in vue-router, otherwise it won't be recognized as one and view route updates won't be triggered.

**Comment by suryadana** [comment]
Not stop when condition press button F5.

**Comment by lgarczyn** [comment]
I've had this issue, the doc did not mention I needed to add:

``` js
Component.registerHooks([
    'beforeRouteEnter'
    'beforeRouteUpdate',
    'beforeRouteLeave'
]);
```

before my typescript class-component declaration.

As stated, it only works for root components, declared in the router declaration

**Comment by kirandeep123** [comment]
@lgarczyn thanks a lot. I was scratching my head on this for many hours.
