### ISSUE TITLE
onError not called on next false

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-router#2956]
https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L107
not called on return false, should be called, or add global onAbort hook.
Also npm src, doesn't contain subdirs, there only 4-5 files in root src, nothing else.

@posva

**Comment by posva** [comment]
Don't hijack the issue helper. A repro is required 
The file issue has been fixed and will appear in the next release

**Comment by afwn90cj93201nixr2e1re** [comment]
As i said, just check the code, you missed onError callback calling here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L107    , but checking for false here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L153

simple code:
beforeRouteEnter(to, from, next){
if(1){next(new Error('This gonna call onError global route Hook');return;}
if(1){next(false);return;}//but that's not, this call only onAbort local route link.
}

i know, thats expected coz that's onError which mean calback should be called only on Error, but how we should operate/hook on false next on global level, which also stop routing?

I think you should add ||error===false
or create new global hook for router which called onCancel.


You really need repo gor this?

**Comment by afwn90cj93201nixr2e1re** [comment]
@posva

**Comment by afwn90cj93201nixr2e1re** [comment]
@posva ping again...
