### ISSUE TITLE
$route.matched[0].name - Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by PrimozRome** [vuejs/vue-router#652]
Based on the forum discussion [here](http://forum.vuejs.org/topic/5193/vue-router-2-0-route-matched-0-name-cannot-read-property-name-of-undefined) I am opening this issue.

I am getting this error `Cannot read property 'name' of undefined` on this line in my Navbar.vue component template `:class="{ 'bg-success': $route.matched[0].name === name }"`. Basically I am checking in which section I am by checking the top matched route...

This is my vue router config:

``` js
const router = new VueRouter({
  mode: 'history',
  saveScrollPosition: true,
  transitionOnLoad: true,
  linkActiveClass: 'is-active',
  routes: [

    // AUTH
    {
      path: '/auth',
      component: Auth,
      redirect: '/auth/login',
      meta: { guest: true },
      children: [
        { path: 'login', component: Login },
        { path: 'logout', alias: '/logout', meta: { logout: true } },
        { path: 'forgot-password', component: Forgot }
      ]
    },
    {
      path: '/unauthorized',
      name: 'unauthorized',
      component: Unauthorised
    },

    // DASHBOARD
    {
      path: '/',
      redirect: store.state.globals.menu.dashboard.link
    },
    {
      path: store.state.globals.menu.dashboard.link,
      name: store.state.globals.menu.dashboard.section,
      component: Dashboard,
      meta: { auth: true }
    },

    // USERS
    {
      path: store.state.globals.menu.users.link,
      name: store.state.globals.menu.users.section,
      component: Users,
      meta: { auth: true, permission: store.state.globals.menu.users.protected },
      children: [
        { path: 'create', component: UserView, meta: { update: false } },
        { path: ':id', component: UserView, meta: { update: true } }
      ]
    },

    // DEPARTMENTS
    {
      path: store.state.globals.menu.departments.link,
      name: store.state.globals.menu.departments.section,
      component: Departments,
      meta: { auth: true, permission: store.state.globals.menu.users.protected },
      children: [
        { path: 'create', component: DepartmentView, meta: { update: false } },
        { path: ':id', component: DepartmentView, meta: { update: true } }
      ]
    }
  ]
})

router.beforeEach((route, redirect, next) => {
  if (route.matched.some(m => m.meta.auth) && !store.state.auth.authenticated) {
    redirect({
      path: '/auth/login'
    })
  } else if (route.matched.find(m => m.meta.logout)) {
    auth.logout()
    redirect({
      path: '/auth/login'
    })
  } else if (route.meta.permission && !store.state.auth.user.permissions[route.meta.permission]) {
    redirect({
      name: 'unauthorized'
    })
  } else if (route.matched.some(m => m.meta.guest) && store.state.auth.authenticated) {
    redirect({
      name: 'dashboard'
    })
  }
  next()
})
```

This happens only when I am at `/users` URL and hit refresh... I log this.$route in created event of Navbar.vue and I am seeing that `$route.matched[0].name` is `null` and fullPath is something strange, see:

![screen shot 2016-09-11 at 21 02 39](https://cloud.githubusercontent.com/assets/1180467/18421120/49cccf00-7882-11e6-8489-7813d5a9443c.png)

When I do the same refresh on the `/dashboard` URL this error is not present and `$route` object is ok

![screen shot 2016-09-11 at 21 15 59](https://cloud.githubusercontent.com/assets/1180467/18421126/66c34530-7882-11e6-90db-945747f68718.png)

If I am navigating from `/dashboard` to `/users` without hard refresh of browser tab, this error is not reported.

It's hard to reproduce this on JSFiddle as there is many components involved in this project, but if it helps I can share the BitBucket repo.

**Comment by fnlctrl** [comment]
This actually looks like a usage problem rather than a bug, following up from the forum post.
If you do believe there is a bug, please provide an isolated reproduction on jsfiddle. You can ignore vuex in the repro and use literals in your router config, and simulate ajax calls with setTimeout.

**Comment by PrimozRome** [comment]
I will try to reproduce with jsFiddle or something

**Comment by PrimozRome** [comment]
Ok I have come up with something here...

https://jsfiddle.net/n78ecfj9/4/
- I don't know why router view is not showing
- but the error message is there, the same as I get
- not sure though if for the same reason if in my app
- can you please check the forum discussion, I have added new post where I have narrowed down my problem http://forum.vuejs.org/topic/5193/vue-router-2-0-route-matched-0-name-cannot-read-property-name-of-undefined. I really dont know if this is a bug or my miss-usage. But I for sure have nothing strange going on.

**Comment by fnlctrl** [comment]
Fixed and running version here: https://jsfiddle.net/La7zw6wv/4/

(Added a router.push('/') because jsfiddle may have some issues with url.)
Note: you have typos of `dashbaord` everywhere

After fixing the typos, it gives Uncaught RangeError: Maximum call stack size exceeded, which caused by your bugged logic in `beforeEach`

``` js
if (route.matched.some(m => m.meta.auth) && true) {
    redirect({
      path: '/auth/login'
    })
  } else if (route.matched.some(m => m.meta.guest) && true) {
    redirect({
      name: 'dashboard'
    })
  }
```

where auth has `meta: { guest: true }`, and dashboard has `meta: { auth: true }` so they will redirect to one another until stackoverflow.

Now, after commenting that logic everything works fine.

The issue of `$route.matched[0]`  being undefined is the logic (and the typo) you put that stopped vue-router from matching. (Hint: you can actuallly just use `$route.name` instead of `$route.matched[0].name`.)

So I'm closing this issue as it's not a bug.

**Comment by PrimozRome** [comment]
Hmm this is strange... i tried removing everything in `beforeEach` in my app but I still get the same error. And even if I have that in I don't get Uncaught RangeError: Maximum call stack size exceeded... 

I am not getting it.

**Comment by PrimozRome** [comment]
> (Hint: you can actuallly just use $route.name instead of $route.matched[0].name.)

Tried but it doesn't work in users in the subroutes, becuase subroutes dont have this name. I eventually need to check in the subroutes if belong to the main 'name' section which is 'users'... That why I am checking the matched[0]...

**Comment by fnlctrl** [comment]
> That why I am checking the matched[0]...

I see.. 

> I am still not getting it.

You can compare your code to the working fiddle (https://jsfiddle.net/La7zw6wv/4/) to debug for the cause of the errors, but I'm afraid there's nothing more I can do to help.

**Comment by PrimozRome** [comment]
> You can compare your code to the working fiddle (https://jsfiddle.net/La7zw6wv/4/) to debug for the cause of the errors, but I'm afraid there's nothing more I can do to help

Yeah I have seen my error. Please see bellow I have fixed that but as I mentioned it's impossible to reproduce this use case on jsFiddle. Please see bellow why...

I have fixed the logic in the `beforeEach` and made new version https://jsfiddle.net/La7zw6wv/5/. It's still working as your fixed example.

It's impossible to reproduce this in the jsFiddle as I can not hit refresh when being on `/users` route. In my app the error happens only in this use case... I enter in the browser URL `http://localhost:8080/users` and refresh the entire browser tab (Command-R) page on this route... -> I get the error!

If I load the app in Dahsboard `http://localhost:8080/dashboard` and do the same refresh the error does not happen. And if I navigate trough router-link to the users from here also no error.

I don't know how I can show you that?

**Comment by fnlctrl** [comment]
> I enter in the browser URL http://localhost:8080/users and refresh the entire browser tab (Command-R) page on this route... -> I get the error!

Does that happen when you remove everything else but `next()` in your `beforeEach` hook? 
If so, there may be a bug. If not, you'll have to debug your beforeEach hook.

**Comment by PrimozRome** [comment]
> Does that happen when you remove everything else but next() in your beforeEach hook?

Have tried removing `next()` in `beforeEach`... Error still happens

![screen shot 2016-09-12 at 10 22 10](https://cloud.githubusercontent.com/assets/1180467/18429280/d32356ca-78d2-11e6-910a-471eb47fc21e.png)

**Comment by fnlctrl** [comment]
There's got to be something you wrote that is blocking router's matching process...
For now, try if adding `$route.matched[0] &&`  works

`$route.matched[0] && $route.matched[0].name === 'dashboard')`

**Comment by PrimozRome** [comment]
> For now, try if adding $route.matched[0] && works

Ok If I do this I don't get the error anymore... 

> There's got to be something you wrote that is blocking router's matching process...

You mean as in `beforeEach`? I only have this and it doesn affects the error if I completely remove it

```
router.beforeEach((route, redirect, next) => {
  if (route.matched.some(m => m.meta.auth) && !store.state.auth.authenticated) {
    console.log('auth: true')
    redirect({
      path: '/auth/login'
    })
  } else if (route.matched.find(m => m.meta.logout)) {
    auth.logout()
    redirect({
      path: '/auth/login'
    })
  } else if (route.meta.permission && !store.state.auth.user.permissions[route.meta.permission]) {
    redirect({
      name: 'unauthorized'
    })
  } else if (route.matched.some(m => m.meta.guest) && store.state.auth.authenticated) {
    console.log('gues: true')
    redirect({
      name: 'dashboard'
    })
  }
  next()
})

```

**Comment by IamCharmaineJoy** [comment]
I have the same error but my solution is very simple
because i just happen to redo my function .
```
mixins : goTo (payload) {
      this.$router.push(payload)
    }
component method: 
 move () {
        this.goTo('/home/' + localStorage.getItem('username'))
      }

wrong call : @click="goTo(move())
right call: @click="move() 
```
